services:
  web:
    build: .
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.web.rule=Host(`bnmwag.dev`)"
    #   - "traefik.http.routers.web.entrypoints=websecure"
    #   - "traefik.http.routers.web.tls.certresolver=myresolver"
    ports:
      - 4321:4321
    volumes:
      - node_modules:/home/node/app/node_modules
    # networks:
    #   - net_tr

networks:
  traefik-public:
    external: true

volumes:
  node_modules: